# Generated by Django 4.2 on 2026-02-19 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career_path', models.CharField(blank=True, choices=[('software_engineer', 'Software Engineer'), ('data_scientist', 'Data Scientist'), ('web_developer', 'Web Developer'), ('product_manager', 'Product Manager'), ('designer', 'UI/UX Designer'), ('devops', 'DevOps / Cloud Engineer'), ('cybersecurity', 'Cybersecurity Specialist'), ('ai_ml', 'AI / Machine Learning Engineer'), ('entrepreneur', 'Entrepreneur'), ('other', 'Other')], max_length=50)),
                ('primary_goal', models.CharField(blank=True, choices=[('get_job', 'Land My First Job'), ('switch_career', 'Switch Careers'), ('freelance', 'Start Freelancing'), ('startup', 'Build a Startup'), ('upskill', 'Upskill & Grow'), ('research', 'Pursue Research / Academia')], max_length=50)),
                ('interests', models.CharField(blank=True, help_text='Comma-separated list of interest keys', max_length=255)),
                ('experience_level', models.CharField(blank=True, choices=[('beginner', 'Beginner (0–1 years)'), ('intermediate', 'Intermediate (2–4 years)'), ('experienced', 'Experienced (5–9 years)'), ('expert', 'Expert (10+ years)')], max_length=20)),
                ('learning_style', models.CharField(blank=True, choices=[('videos', 'Video Tutorials'), ('books', 'Books & Articles'), ('projects', 'Hands-on Projects'), ('courses', 'Structured Courses'), ('mentorship', 'Mentorship & Coaching')], max_length=30)),
                ('profile_complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
