# Generated by Django 4.2 on 2026-02-19 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0003_quizresult'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuizResult',
        ),
    ]
